name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Statistics
        uses: cicirello/user-statistician@v1
        with:
          image-file: stats.svg
          colors: dark
          include-title: true
          custom-title: Yash Vardhan Singh - GitHub Statistics
          animated-language-chart: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
